apiVersion: v1
kind: ConfigMap
metadata:
  name: incident-ai-config
  namespace: incident-ai
data:
  DEMO_MODE: "false"
  LLM_PROVIDER: openai
  CELERY_ENABLED: "true"
  AWS_REGION: eu-central-1
  APNS_BUNDLE_ID: com.erykszczesniak.IncidentAI
