import logging
from typing import Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.ai.client import LLMClient
from app.ai.redaction import redact
from app.core.config import Settings
from app.core.errors import AppError
from app.domain.incidents import add_event, incident_dict, require_incident
from app.repository.models import Alert, Analysis, LogEntry, TimelineEvent

logger = logging.getLogger("incident_ai.analysis")
REVIEW_CAVEAT = "AI analysis is an assistive suggestion. An engineer must verify the evidence and approve remediation."


def redact_context(value: Any) -> Any:
    if isinstance(value, str):
        return redact(value)
    if isinstance(value, list):
        return [redact_context(item) for item in value]
    if isinstance(value, dict):
        return {key: redact_context(item) for key, item in value.items()}
    return value


async def latest_analysis(session: AsyncSession, incident_id: str) -> Analysis:
    analysis = await session.scalar(
        select(Analysis)
        .where(Analysis.incident_id == incident_id)
        .order_by(Analysis.created_at.desc(), Analysis.id.desc())
        .limit(1)
    )
    if analysis is None:
        raise AppError(
            "analysis_not_found", "Run analysis to create an assistive report", 404
        )
    return analysis


async def build_context(session: AsyncSession, incident_id: str) -> dict[str, Any]:
    incident = await require_incident(session, incident_id)
    # Most recent context, bounded before calling any provider.
    logs = list(
        (
            await session.scalars(
                select(LogEntry)
                .where(LogEntry.incident_id == incident_id)
                .order_by(LogEntry.timestamp.desc())
                .limit(200)
            )
        ).all()
    )
    events = list(
        (
            await session.scalars(
                select(TimelineEvent)
                .where(TimelineEvent.incident_id == incident_id)
                .order_by(TimelineEvent.created_at.desc())
                .limit(100)
            )
        ).all()
    )
    alerts = list(
        (
            await session.scalars(
                select(Alert).where(Alert.incident_id == incident_id).limit(50)
            )
        ).all()
    )
    remaining = 100_000
    log_context: list[dict[str, Any]] = []
    for entry in logs:
        if remaining <= 0:
            break
        message = entry.message[: min(8192, remaining)]
        remaining -= len(message)
        log_context.append(
            {
                "timestamp": entry.timestamp.isoformat(),
                "level": entry.level,
                "message": message,
            }
        )
    return redact_context(
        {
            "incident": incident_dict(incident),
            "logs": list(reversed(log_context)),
            "timeline": [
                {
                    "timestamp": event.created_at.isoformat(),
                    "kind": event.kind,
                    "message": event.message[:2000],
                }
                for event in reversed(events)
            ],
            "alerts": [
                {
                    "source": alert.source,
                    "title": alert.title,
                    "description": alert.description[:4000],
                }
                for alert in alerts
            ],
            "context_limits": {
                "max_logs": 200,
                "max_log_characters": 100000,
                "max_timeline_events": 100,
            },
        }
    )


async def analyze_incident(
    session: AsyncSession, incident_id: str, llm: LLMClient, settings: Settings
) -> Analysis:
    context = await build_context(session, incident_id)
    result = await llm.analyze(context)
    values = redact_context(result.model_dump())
    if REVIEW_CAVEAT not in values["caveats"]:
        values["caveats"].append(REVIEW_CAVEAT)
    analysis = Analysis(incident_id=incident_id, **values)
    session.add(analysis)
    add_event(
        session,
        incident_id,
        "analysis_completed",
        f"Assistive analysis generated by {result.provider}. Evidence requires engineer review.",
    )
    # Embedding outages must not discard a usable analysis.
    try:
        incident = await require_incident(session, incident_id)
        vector = await llm.embed(
            f"{incident.title}\n{incident.service}\n{result.summary}\n{result.probable_cause}"
        )
        if vector:
            incident.embedding = vector
            incident.embedding_model = settings.embedding_model
    except Exception as exc:
        logger.info(
            "Embedding unavailable; lexical search remains available",
            extra={"exception_type": type(exc).__name__},
        )
    await session.flush()
    return analysis
